name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-latest, ubuntu-latest, windows-latest]
        platform: [windows-latest, ubuntu-latest]
        # target: [x86_64-pc-windows-msvc]
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    env:
      OPENCV_VERSION: 4.6.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          default: true
          # target: ${{ matrix.target }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
          
      - name: Build
        env:
          OS_FAMILY: ${{ runner.os }}
        run: ci/install.sh
        shell: bash

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: target/release/bundle/**/*
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/bundle/**/*"
          tag: "v1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}
          # bodyFile: "body.md"
      # - name: Install app dependencies and build web
      #   run: yarn && yarn build

      # - name: Build the app
      #   uses: tauri-apps/tauri-action@v0.3

      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
      #     releaseName: 'v__VERSION__'
      #     releaseBody: 'See the assets to download this version and install.'
      #     releaseDraft: true
      #     prerelease: false
